
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myrailsmap_development

test:
  <<: *default
  database: myrailsmap_test

production:
  <<: *default
  database: myrailsmap_production
  username: myrailsmap
  password: <%= ENV['MYRAILSMAP_DATABASE_PASSWORD'] %>
